services:
    bundles_inventario.admin.inv_entrada:
        class: Bundles\InventarioBundle\Admin\InvEntradaAdmin
        arguments: [~, Bundles\InventarioBundle\Entity\InvEntrada, BundlesInventarioBundle:InvEntradaAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Inventarios, label: Entradas}

    bundles_inventario.admin.inv_entradadetalle:
        class: Bundles\InventarioBundle\Admin\InvEntradadetalleAdmin
        arguments: [~, Bundles\InventarioBundle\Entity\InvEntradadetalle, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, show_in_dashboard: false}

    #bundles_inventario.admin.inv_auxiliar_producto:
    #    class: Bundles\InventarioBundle\Admin\InvAuxiliarProductoAdmin
    #    arguments: [~, Bundles\CatalogosBundle\Entity\CtlProducto, BundlesInventarioBundle:InvAuxiliarProducto]
    #    tags:
    #        - {name: sonata.admin, manager_type: orm, group: Inventarios, label: Auxiliar de productos}


    bundles_inventario.admin.inv_producto_mov:
        class: Bundles\InventarioBundle\Admin\InvProductoMovAdmin
        arguments: [~, Bundles\InventarioBundle\Entity\InvProductoMov, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Inventarios, label: Crear producto-lote}

    bundles_inventario.admin.inv_producto_mov_ventas:
        class: Bundles\InventarioBundle\Admin\InvProductoMovVentasAdmin
        arguments: [~, Bundles\InventarioBundle\Entity\InvProductoMovVentas, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, show_in_dashboard: false}

    bundles_inventario.admin.inv_cierre_periodo:
        class: Bundles\InventarioBundle\Admin\InvCierrePeriodoAdmin
        arguments: [~, Bundles\InventarioBundle\Entity\InvCierrePeriodo, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, show_in_dashboard: false}
