services:
    bundles_cxc.admin.mnt_empleado_zona:
        class: Bundles\CxcBundle\Admin\MntEmpleadoZonaAdmin
        arguments: [~, Bundles\CxcBundle\Entity\MntEmpleadoZona, BundlesCxcBundle:MntEmpleadoZonaAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, show_in_dashboard: false}

    bundles_cxc.admin.cxc_cobro:
        class: Bundles\CxcBundle\Admin\CxcCobroAdmin
        arguments: [~, Bundles\CxcBundle\Entity\CxcCobro, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: CXC, label: Cobros}

    bundles_cxc.admin.cxc_cobro_reporte:
        class: Bundles\CxcBundle\Admin\CxcCobroReporteAdmin
        arguments: [~, Bundles\CxcBundle\Entity\CxcCobroReporte, BundlesCxcBundle:CxcCobroReporteAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: CXC, label: Informe diario}
