shtumi_useful :
    dependent_filtered_entities:
        muni_por_depto:
            class: BundlesCatalogosBundle:CtlMunicipio
            parent_property: idDepartamento
            property: nombre
            role: ROLE_USER
            no_result_msg: 'No hay municipios encontrados'
            order_property: nombre
            order_direction: ASC
