services:
    bundles_factura.admin.fac_factura:
        class: Bundles\FacturaBundle\Admin\FacFacturaAdmin
        arguments: [~, Bundles\FacturaBundle\Entity\FacFactura, BundlesFacturaBundle:FacFacturaAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Ventas, label: Facturar}

    bundles_factura.admin.fac_facturadetalle:
        class: Bundles\FacturaBundle\Admin\FacFacturadetalleAdmin
        arguments: [~, Bundles\FacturaBundle\Entity\FacFacturadetalle, BundlesFacturaBundle:FacFacturadetalleAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, show_in_dashboard: false}

    bundles_factura.admin.fac_notaremision:
        class: Bundles\FacturaBundle\Admin\FacNotaremisionAdmin
        arguments: [~, Bundles\FacturaBundle\Entity\FacNotaremision, BundlesFacturaBundle:FacNotaremisionAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Ventas, label: Notas de remisión}

    bundles_factura.admin.fac_notaremisiondetalle:
        class: Bundles\FacturaBundle\Admin\FacNotaremisiondetalleAdmin
        arguments: [~, Bundles\FacturaBundle\Entity\FacNotaremisiondetalle, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, show_in_dashboard: false}
