services:
#    bundles_catalogos.admin.ctl_cliente:
#        class: Bundles\CatalogosBundle\Admin\CtlClienteAdmin
#        arguments: [~, Bundles\CatalogosBundle\Entity\CtlCliente, SonataAdminBundle:CRUD]
#        tags:
#            - {name: sonata.admin, manager_type: orm, group: admin, label: CtlCliente}
    bundles_catalogos.admin.ctl_cliente:
        class: Bundles\CatalogosBundle\Admin\CtlClienteAdmin
        arguments: [~, Bundles\CatalogosBundle\Entity\CtlCliente, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Catálogos, label: Clientes}

    bundles_catalogos.admin.ctl_zona:
        class: Bundles\CatalogosBundle\Admin\CtlZonaAdmin
        arguments: [~, Bundles\CatalogosBundle\Entity\CtlZona, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Catálogos, label: Zonas}

    bundles_catalogos.admin.ctl_estado:
        class: Bundles\CatalogosBundle\Admin\CtlEstadoAdmin
        arguments: [~, Bundles\CatalogosBundle\Entity\CtlEstado, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Catálogos, label: Estados de proceso}

    bundles_catalogos.admin.ctl_banco:
        class: Bundles\CatalogosBundle\Admin\CtlBancoAdmin
        arguments: [~, Bundles\CatalogosBundle\Entity\CtlBanco, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Catálogos, label: Bancos}

    bundles_catalogos.admin.ctl_cargofuncional:
        class: Bundles\CatalogosBundle\Admin\CtlCargofuncionalAdmin
        arguments: [~, Bundles\CatalogosBundle\Entity\CtlCargofuncional, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Catálogos, label: Cargo funcional}

    bundles_catalogos.admin.ctl_empleado:
        class: Bundles\CatalogosBundle\Admin\CtlEmpleadoAdmin
        arguments: [~, Bundles\CatalogosBundle\Entity\CtlEmpleado, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Catálogos, label: Empleados}

    bundles_catalogos.admin.ctl_categoria:
        class: Bundles\CatalogosBundle\Admin\CtlCategoriaAdmin
        arguments: [~, Bundles\CatalogosBundle\Entity\CtlCategoria, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Catálogos, label: Categoría productos}

    bundles_catalogos.admin.ctl_unidad:
        class: Bundles\CatalogosBundle\Admin\CtlUnidadAdmin
        arguments: [~, Bundles\CatalogosBundle\Entity\CtlUnidad, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Catálogos, label: Cantidad Unitaria}

    bundles_catalogos.admin.ctl_producto:
        class: Bundles\CatalogosBundle\Admin\CtlProductoAdmin
        arguments: [~, Bundles\CatalogosBundle\Entity\CtlProducto, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Catálogos, label: Productos}

    bundles_catalogos.admin.ctl_tipoentrada:
        class: Bundles\CatalogosBundle\Admin\CtlTipoentradaAdmin
        arguments: [~, Bundles\CatalogosBundle\Entity\CtlTipoentrada, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Catálogos, label: Tipo de entrada}

    bundles_catalogos.admin.ctl_proveedor:
        class: Bundles\CatalogosBundle\Admin\CtlProveedorAdmin
        arguments: [~, Bundles\CatalogosBundle\Entity\CtlProveedor, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Catálogos, label: Proveedores}



    # services para activar menu personalizados
    # -inicio

    bundles_catalogos.menus_builder:
        class: Bundles\CatalogosBundle\Menu\MenusBuilder
        arguments: ["@knp_menu.factory"]

    bundles_catalogos.menu.main:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: bundles_catalogos.menus_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu
           
    bundles_catalogos.menu.sidebar:
        class: Knp\Menu\MenuItem
        factory_service: bundles_catalogos.menus_builder
        factory_method: createSidebarMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: sidebar } # Named "sidebar" this time  
            
        # fin de service para activar menu personalizados

    bundles_catalogos.admin.cfg_formato_documento:
        class: Bundles\CatalogosBundle\Admin\CfgFormatoDocumentoAdmin
        arguments: [~, Bundles\CatalogosBundle\Entity\CfgFormatoDocumento, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Admin, label: Formatos de documentos}

    bundles_catalogos.admin.cfg_plantilla:
        class: Bundles\CatalogosBundle\Admin\CfgPlantillaAdmin
        arguments: [~, Bundles\CatalogosBundle\Entity\CfgPlantilla, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Admin, label: Plantilla}

    bundles_catalogos.admin.ctl_font_name:
        class: Bundles\CatalogosBundle\Admin\CtlFontNameAdmin
        arguments: [~, Bundles\CatalogosBundle\Entity\CtlFontName, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Admin, label: Nombres de tipos de letras}

    bundles_catalogos.admin.ctl_font_size:
        class: Bundles\CatalogosBundle\Admin\CtlFontSizeAdmin
        arguments: [~, Bundles\CatalogosBundle\Entity\CtlFontSize, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Admin, label: Tamaño de letra}
